# Generated by Django 5.0.6 on 2024-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="premium",
            new_name="is_premium",
        ),
        migrations.AddField(
            model_name="plan",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                default="basic",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
