# Generated by Django 5.0.6 on 2024-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_rename_premium_plan_is_premium_plan_billing_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="stripe_plan_id",
            field=models.CharField(
                default="default_stripe_plan_id", max_length=255, unique=True
            ),
        ),
    ]
