# Generated by Django 5.0.6 on 2024-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_plan_stripe_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(default="usd", max_length=10),
        ),
        migrations.AlterField(
            model_name="plan",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_plan_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
